rvm:
 - 1.9.3
 - 2.0
 - 2.1
 - 2.2.4
 - 2.3.1
 - ruby-head

gemfile:
 - Gemfile

before_install: gem update bundler
script: bundle exec rake test

matrix:
  allow_failures:
    - rvm: 1.9.3
    - rvm: ruby-head
