rvm:
 - 1.9.3
 - 2.0
 - 2.1
 - 2.2.4
 - 2.3.1
 - ruby-head

gemfile:
 - Gemfile
 - Gemfile.v0.12

before_install: gem update bundler
script: bundle exec rake test

sudo: false

matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 1.9.3
      gemfile: Gemfile
    - rvm: 2.0
      gemfile: Gemfile
