version: 2.1
orbs:
  ruby: circleci/ruby@1.8
jobs:
  test:
    parameters:
      ruby-version:
        type: string
    docker:
      - image: cimg/ruby:<< parameters.ruby-version >>
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Run tests
          command: bundle exec rake test
workflows:
  version: 2
  test:
    jobs:
      - test:
          matrix:
            parameters:
              ruby-version: [ "2.4", "2.5", "2.6", "2.7", "3.0", "3.1" ]
